---
title: "Hospitalization model"
output: html_notebook
---

```{r}
#### load libraries ####
library(readr)
library(dplyr)
library(pROC)
library(finalfit)
library(ggplot2)
library(ResourceSelection)
library(vcdExtra)
library(PredictABEL)
library(gtools)
```

```{r}
##### setup #####
rm(list=ls())
data <- read_csv('covid_dataset.csv')
# removing individuals with missing info
data <- data[complete.cases(data), ]
colnames(data)
```


```{r}
#### adjust var type ####
data$`Dem;;gender` <- apply(data["Dem;;gender"], MARGIN=2, function(x) as.factor(x))

# age per 10 years 
data$`Dem;;age` <- apply(data["Dem;;age"], MARGIN=2, function(x) as.numeric(x))
data$`Dem;;age` <- apply(data["Dem;;age"], MARGIN=2, function(x) x/10)

data$`Dem;;race` <- apply(data["Dem;;race"], MARGIN=2, function(x) as.factor(x))

# income per $10,000 
data$`Dem;;zip_code_income` <- apply(data["Dem;;zip_code_income"], MARGIN=2, function(x) as.numeric(x))
data$`Dem;;zip_code_income` <- apply(data["Dem;;zip_code_income"], MARGIN=2, function(x) x/10)

data$`Dem;;covid_status` <- apply(data["Dem;;covid_status"], MARGIN=2, function(x) as.numeric(x))
data$`Dem;;smoking` <- apply(data["Dem;;smoking"], MARGIN=2, function(x) as.factor(x))
data$`Dem;;partners_employee` <- apply(data["Dem;;partners_employee"], MARGIN=2, function(x) as.factor(x))
data$hosp <- apply(data["hosp"], MARGIN=2, function(x) as.numeric(x))
data$expired <- apply(data["expired"], MARGIN=2, function(x) as.numeric(x))
# covid+ only
sum(data$`Dem;;covid_status`)
dim(data)
data <- dplyr::select(data, -c("Dem;;covid_status"))
```
```{r}
#### ranking classes based on # patients ####
summary(data$`Dem;;race`)
data$`Dem;;race` <- factor(data$`Dem;;race`, levels = c("White", "Hispanic", "Black", "Other/Not recorded"))

summary(data$`Dem;;smoking`)
data$`Dem;;smoking` <- factor(data$`Dem;;smoking`, levels = c("Never", "Current", "Ever", "Unknown"))
```

```{r}
#### creating derivation (non-employees) and validation (MGB employees) ####
employees <- data[which(data$`Dem;;partners_employee`==1),]
non_employees <- data[which(data$`Dem;;partners_employee`==0),]

paste("Cohort N:", dim(data)[1])
paste("non_employees N:", dim(non_employees)[1], ", #hosp:", dim(non_employees[which(non_employees$hosp == 1),])[1])
paste("employees N:", dim(employees)[1], ", #hosp:", dim(employees[which(employees$hosp == 1),])[1])

# removing deceased flag for hospitalization analysis
employees_deceased <- employees$expired
non_employees_deceased <- non_employees$expired
employees <- dplyr::select(employees, -c("Dem;;partners_employee", "expired"))
non_employees <- dplyr::select(non_employees, -c("Dem;;partners_employee", "expired"))
```

```{r}
#### model for predicting hospitalization OR/estimates ####
paste("Predicting hospitalization")
paste("Training set (non-employees) N:", dim(non_employees)[1], ", #hosp:", dim(non_employees[which(non_employees$hosp == 1),])[1])
# fitting the model
train_mod <- glm(hosp ~ ., data=non_employees, family=binomial)
summary(train_mod)
cbind(exp(cbind(OR = coef(train_mod), confint(train_mod))), coef(summary(train_mod))[,4])

```
```{r}
#### validating the model ####
paste("Testing (employees) N:", dim(employees)[1], ", #hosp:", dim(employees[which(employees$hosp == 1),])[1])
predicted_values <- predict(train_mod, newdata=employees, type="response")
roc_obj <- roc(response = employees$hosp, predictor = predicted_values)
auc(roc_obj)

# calculating auc
ci.auc(roc_obj, conf.level=0.95, method=c("delong", "bootstrap"), boot.n = 2000, boot.stratified = TRUE, reuse.auc=TRUE, progress = getOption("pROCProgress")$name, parallel=FALSE)
coords(roc_obj, "best", ret = "threshold", transpose = TRUE)

```


```{r}
#### AUC after cutoff ####
cutoff <- 0.2909958

predicted_values <- predict(train_mod, newdata=employees, type="response")
predicted_values_w_cutoff <- lapply(predicted_values, function(x) 
  {ifelse(x>=cutoff, 1, 0)}
)
predicted_values_w_cutoff <- as.double(predicted_values_w_cutoff)
roc_obj_w_cutoff <- roc(response = employees$hosp, predictor = predicted_values_w_cutoff)
auc(roc_obj_w_cutoff)
ci.auc(roc_obj_w_cutoff, conf.level=0.95, method=c("delong", "bootstrap"), boot.n = 2000, boot.stratified = TRUE, reuse.auc=TRUE, progress = getOption("pROCProgress")$name, parallel=FALSE)

actual_class <- employees$hosp
remaining_actual_val <- actual_class[which(predicted_values < cutoff)]
remaining_predicted <- predicted_values[which(predicted_values < cutoff)]
roc_obj_remaining <- roc(response = remaining_actual_val, predictor = remaining_predicted)
auc(roc_obj_remaining)
ci.auc(roc_obj_remaining, conf.level=0.95, method=c("delong", "bootstrap"), boot.n = 2000, boot.stratified = TRUE, reuse.auc=TRUE, progress = getOption("pROCProgress")$name, parallel=FALSE)
coords(roc_obj_remaining, "best", ret = "threshold", transpose = TRUE)
```
```{r}
### calculating auc for the 3 categories of low, intermediate, and high risk groups ####
three_class <- employees
three_class$predicted_hosp <- predicted_values

cutoff <- 0.2909958
cutoff2 <- 0.1597124
three_class$predicted_hosp <- as.double(lapply(three_class$predicted_hosp, function(x) {ifelse(x>cutoff, 2, {ifelse(x>cutoff2, 1, 0)})}))


data <- three_class
t <- roc(response = data$hosp, predictor = data$predicted_hosp)
auc(t)
ci.auc(t, conf.level=0.95, method=c("delong", "bootstrap"), boot.n = 2000, boot.stratified = TRUE, reuse.auc=TRUE, progress = getOption("pROCProgress")$name, parallel=FALSE)

```

```{r}
#### calibration hospitalization ####
data1 <- employees
p <- predict(train_mod, newdata=data1)
group <- cut(p, c(-Inf, quantile(p,(1:9)/10, Inf)))
fit1 <- glm(hosp ~ offset(p), family=binomial, data=data1)
hoslem.test(employees$hosp, inv.logit(fit1$coefficients[1] + predict(train_mod, newdata=employees)), g = 15)
```

